//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网址.
        /// </summary>
        public static string AddressUrl {
            get {
                return ResourceManager.GetString("AddressUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device in disable status.
        /// </summary>
        public static string API_DeviceDisableStatus {
            get {
                return ResourceManager.GetString("API_DeviceDisableStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InnerExceptions.
        /// </summary>
        public static string API_InnerExceptions {
            get {
                return ResourceManager.GetString("API_InnerExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NG.
        /// </summary>
        public static string API_NG {
            get {
                return ResourceManager.GetString("API_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string API_OK {
            get {
                return ResourceManager.GetString("API_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Params not exist.
        /// </summary>
        public static string API_ParamsNotExist {
            get {
                return ResourceManager.GetString("API_ParamsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平台状态.
        /// </summary>
        public static string AuditStatus {
            get {
                return ResourceManager.GetString("AuditStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 声明.
        /// </summary>
        public static string Declaration {
            get {
                return ResourceManager.GetString("Declaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电商平台.
        /// </summary>
        public static string EcommercePlatform {
            get {
                return ResourceManager.GetString("EcommercePlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 组类型.
        /// </summary>
        public static string GroupType {
            get {
                return ResourceManager.GetString("GroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片1.
        /// </summary>
        public static string Image01Url {
            get {
                return ResourceManager.GetString("Image01Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片2.
        /// </summary>
        public static string Image02Url {
            get {
                return ResourceManager.GetString("Image02Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片3.
        /// </summary>
        public static string Image03Url {
            get {
                return ResourceManager.GetString("Image03Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片4.
        /// </summary>
        public static string Image04Url {
            get {
                return ResourceManager.GetString("Image04Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 介绍.
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公司Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 价格.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品类别.
        /// </summary>
        public static string ProductCategoryId {
            get {
                return ResourceManager.GetString("ProductCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Qrcode_url {
            get {
                return ResourceManager.GetString("Qrcode_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 二维码URL.
        /// </summary>
        public static string QRCodeUrl {
            get {
                return ResourceManager.GetString("QRCodeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 来源.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商户中心门店Id.
        /// </summary>
        public static string StoreId {
            get {
                return ResourceManager.GetString("StoreId", resourceCulture);
            }
        }
    }
}
