//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动作名称.
        /// </summary>
        public static string ActionName {
            get {
                return ResourceManager.GetString("ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action分享.
        /// </summary>
        public static string ActionShare {
            get {
                return ResourceManager.GetString("ActionShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏状态.
        /// </summary>
        public static string ActionStatus {
            get {
                return ResourceManager.GetString("ActionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模板地址.
        /// </summary>
        public static string ActionUrl {
            get {
                return ResourceManager.GetString("ActionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动.
        /// </summary>
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动执行时间.
        /// </summary>
        public static string ActivityExcutedDate {
            get {
                return ResourceManager.GetString("ActivityExcutedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动模板.
        /// </summary>
        public static string ActivityHtmlTemplate {
            get {
                return ResourceManager.GetString("ActivityHtmlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动模板.
        /// </summary>
        public static string ActivityHtmlTemplateID {
            get {
                return ResourceManager.GetString("ActivityHtmlTemplateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动Logo.
        /// </summary>
        public static string ActivityLogoPath {
            get {
                return ResourceManager.GetString("ActivityLogoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动分享.
        /// </summary>
        public static string ActivityShare {
            get {
                return ResourceManager.GetString("ActivityShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动页Url.
        /// </summary>
        public static string ActivityUrl {
            get {
                return ResourceManager.GetString("ActivityUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已发奖品数.
        /// </summary>
        public static string ActualQty {
            get {
                return ResourceManager.GetString("ActualQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动地址.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网址.
        /// </summary>
        public static string AddressUrl {
            get {
                return ResourceManager.GetString("AddressUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 广告名称.
        /// </summary>
        public static string AdsName {
            get {
                return ResourceManager.GetString("AdsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文本内容.
        /// </summary>
        public static string AdsText {
            get {
                return ResourceManager.GetString("AdsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 广告类型.
        /// </summary>
        public static string AdsType {
            get {
                return ResourceManager.GetString("AdsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏后扫码反馈消息.
        /// </summary>
        public static string AfterGameMessage {
            get {
                return ResourceManager.GetString("AfterGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 授权方公众号所设置的微信号.
        /// </summary>
        public static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationUser.
        /// </summary>
        public static string ApplicationUser {
            get {
                return ResourceManager.GetString("ApplicationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ApplicationUserId {
            get {
                return ResourceManager.GetString("ApplicationUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 审核状态.
        /// </summary>
        public static string AuditStatus {
            get {
                return ResourceManager.GetString("AuditStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 授权时间.
        /// </summary>
        public static string AuthorizationTime {
            get {
                return ResourceManager.GetString("AuthorizationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 授权方令牌.
        /// </summary>
        public static string Authorizer_access_token {
            get {
                return ResourceManager.GetString("Authorizer_access_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新令牌.
        /// </summary>
        public static string Authorizer_refresh_token {
            get {
                return ResourceManager.GetString("Authorizer_refresh_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 头像.
        /// </summary>
        public static string AvatarUrl {
            get {
                return ResourceManager.GetString("AvatarUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品图片.
        /// </summary>
        public static string AwardImagePath {
            get {
                return ResourceManager.GetString("AwardImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中奖反馈的文本消息.
        /// </summary>
        public static string AwardMessage {
            get {
                return ResourceManager.GetString("AwardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品.
        /// </summary>
        public static string AwardProduct {
            get {
                return ResourceManager.GetString("AwardProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中奖信息.
        /// </summary>
        public static string Awards {
            get {
                return ResourceManager.GetString("Awards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品等级.
        /// </summary>
        public static string AwardSeq {
            get {
                return ResourceManager.GetString("AwardSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景图片.
        /// </summary>
        public static string BackgroundImage {
            get {
                return ResourceManager.GetString("BackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏前扫码反馈消息.
        /// </summary>
        public static string BeforeGameMessage {
            get {
                return ResourceManager.GetString("BeforeGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大图.
        /// </summary>
        public static string BigImage {
            get {
                return ResourceManager.GetString("BigImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公司信息.
        /// </summary>
        public static string BusinessInfo {
            get {
                return ResourceManager.GetString("BusinessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 子分组.
        /// </summary>
        public static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 城市.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户端装置.
        /// </summary>
        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 线下设备ID.
        /// </summary>
        public static string ClientUniueID {
            get {
                return ResourceManager.GetString("ClientUniueID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公司.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access_token.
        /// </summary>
        public static string Component_access_token {
            get {
                return ResourceManager.GetString("Component_access_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify_ticket.
        /// </summary>
        public static string Component_verify_ticket {
            get {
                return ResourceManager.GetString("Component_verify_ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppID.
        /// </summary>
        public static string ComponentAppID {
            get {
                return ResourceManager.GetString("ComponentAppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppSecret.
        /// </summary>
        public static string ComponentAppSecret {
            get {
                return ResourceManager.GetString("ComponentAppSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string ComponentKey {
            get {
                return ResourceManager.GetString("ComponentKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string ComponentToken {
            get {
                return ResourceManager.GetString("ComponentToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 国家.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建日期.
        /// </summary>
        public static string CreatedTime {
            get {
                return ResourceManager.GetString("CreatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 声明.
        /// </summary>
        public static string Declaration {
            get {
                return ResourceManager.GetString("Declaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 描述.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电商平台.
        /// </summary>
        public static string EcommercePlatform {
            get {
                return ResourceManager.GetString("EcommercePlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束时间.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束时间.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用到期时间.
        /// </summary>
        public static string ExpiredTime {
            get {
                return ResourceManager.GetString("ExpiredTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有效期.
        /// </summary>
        public static string Expires_in {
            get {
                return ResourceManager.GetString("Expires_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流程.
        /// </summary>
        public static string FlowType {
            get {
                return ResourceManager.GetString("FlowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏.
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏编号.
        /// </summary>
        public static string GameCode {
            get {
                return ResourceManager.GetString("GameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏环境.
        /// </summary>
        public static string GameEnvType {
            get {
                return ResourceManager.GetString("GameEnvType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏图片.
        /// </summary>
        public static string GameImage {
            get {
                return ResourceManager.GetString("GameImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏图标.
        /// </summary>
        public static string GameLogo {
            get {
                return ResourceManager.GetString("GameLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏类型.
        /// </summary>
        public static string GameType {
            get {
                return ResourceManager.GetString("GameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏地址.
        /// </summary>
        public static string GameUrl {
            get {
                return ResourceManager.GetString("GameUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性别.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerateUserIdentityAsync.
        /// </summary>
        public static string GenerateUserIdentityAsync {
            get {
                return ResourceManager.GetString("GenerateUserIdentityAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 组名.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 组的类型.
        /// </summary>
        public static string GroupType {
            get {
                return ResourceManager.GetString("GroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公众号头像.
        /// </summary>
        public static string Head_img {
            get {
                return ResourceManager.GetString("Head_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 头像.
        /// </summary>
        public static string Headimgurl {
            get {
                return ResourceManager.GetString("Headimgurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面模板.
        /// </summary>
        public static string HtmlTemplate {
            get {
                return ResourceManager.GetString("HtmlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图标.
        /// </summary>
        public static string IconPath {
            get {
                return ResourceManager.GetString("IconPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片1.
        /// </summary>
        public static string Image01Url {
            get {
                return ResourceManager.GetString("Image01Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片2.
        /// </summary>
        public static string Image02Url {
            get {
                return ResourceManager.GetString("Image02Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片3.
        /// </summary>
        public static string Image03Url {
            get {
                return ResourceManager.GetString("Image03Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片4.
        /// </summary>
        public static string Image04Url {
            get {
                return ResourceManager.GetString("Image04Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分享图标.
        /// </summary>
        public static string ImageLink {
            get {
                return ResourceManager.GetString("ImageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动图片.
        /// </summary>
        public static string ImagePath {
            get {
                return ResourceManager.GetString("ImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片高度.
        /// </summary>
        public static string ImgHeight {
            get {
                return ResourceManager.GetString("ImgHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片宽度.
        /// </summary>
        public static string ImgWidth {
            get {
                return ResourceManager.GetString("ImgWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本地链接.
        /// </summary>
        public static string InsideLink {
            get {
                return ResourceManager.GetString("InsideLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 介绍.
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 锁定.
        /// </summary>
        public static string IsActived {
            get {
                return ResourceManager.GetString("IsActived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否允许重复中奖.
        /// </summary>
        public static string IsAllowedRepeatAward {
            get {
                return ResourceManager.GetString("IsAllowedRepeatAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否启用白名单.
        /// </summary>
        public static string IsEnableWhiteUser {
            get {
                return ResourceManager.GetString("IsEnableWhiteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否显示线上游戏.
        /// </summary>
        public static string IsHasGame {
            get {
                return ResourceManager.GetString("IsHasGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否显示游戏记录.
        /// </summary>
        public static string IsHasGameResult {
            get {
                return ResourceManager.GetString("IsHasGameResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否显示活动介绍.
        /// </summary>
        public static string IsHasIntroduce {
            get {
                return ResourceManager.GetString("IsHasIntroduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否显示注册.
        /// </summary>
        public static string IsHasRegister {
            get {
                return ResourceManager.GetString("IsHasRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否显示中奖列表.
        /// </summary>
        public static string IsHasReward {
            get {
                return ResourceManager.GetString("IsHasReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否显示投票.
        /// </summary>
        public static string IsHasVote {
            get {
                return ResourceManager.GetString("IsHasVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否需要填写中奖信息.
        /// </summary>
        public static string IsNeedAwardInfo {
            get {
                return ResourceManager.GetString("IsNeedAwardInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扫码前是否需要检查限制.
        /// </summary>
        public static string IsNeedCheckBeforScanQRCode {
            get {
                return ResourceManager.GetString("IsNeedCheckBeforScanQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否需要注册.
        /// </summary>
        public static string IsNeedRegister {
            get {
                return ResourceManager.GetString("IsNeedRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否正式使用.
        /// </summary>
        public static string IsPublic {
            get {
                return ResourceManager.GetString("IsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否在当前页快速注册.
        /// </summary>
        public static string IsRegisterInCurrPage {
            get {
                return ResourceManager.GetString("IsRegisterInCurrPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否被扫过.
        /// </summary>
        public static string IsScaned {
            get {
                return ResourceManager.GetString("IsScaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中奖消息.
        /// </summary>
        public static string IsSendAwardMessage {
            get {
                return ResourceManager.GetString("IsSendAwardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否发送消息.
        /// </summary>
        public static string IsSendMessage {
            get {
                return ResourceManager.GetString("IsSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏后发消息.
        /// </summary>
        public static string IsSendWechatAfterGame {
            get {
                return ResourceManager.GetString("IsSendWechatAfterGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏后是否可交互.
        /// </summary>
        public static string IsSendWechatAfterGame4Game {
            get {
                return ResourceManager.GetString("IsSendWechatAfterGame4Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏前发消息.
        /// </summary>
        public static string IsSendWechatBeforeGame {
            get {
                return ResourceManager.GetString("IsSendWechatBeforeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏前是否可交互.
        /// </summary>
        public static string IsSendWechatBeforeGame4Game {
            get {
                return ResourceManager.GetString("IsSendWechatBeforeGame4Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否发送消息.
        /// </summary>
        public static string isSendWeChatMsg {
            get {
                return ResourceManager.GetString("isSendWeChatMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否支持分享.
        /// </summary>
        public static string IsShareAction {
            get {
                return ResourceManager.GetString("IsShareAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏是否支持分享.
        /// </summary>
        public static string IsShareAction4Game {
            get {
                return ResourceManager.GetString("IsShareAction4Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否签到.
        /// </summary>
        public static string IsSigned {
            get {
                return ResourceManager.GetString("IsSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否支持同步.
        /// </summary>
        public static string IsSupportAsync {
            get {
                return ResourceManager.GetString("IsSupportAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否是模板.
        /// </summary>
        public static string IsTemplate {
            get {
                return ResourceManager.GetString("IsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否使用外部链接.
        /// </summary>
        public static string IsUseOutside {
            get {
                return ResourceManager.GetString("IsUseOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jsapi_ticket.
        /// </summary>
        public static string Jsapi_ticket {
            get {
                return ResourceManager.GetString("Jsapi_ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最后登录.
        /// </summary>
        public static string LastLoginTime {
            get {
                return ResourceManager.GetString("LastLoginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点赞次数.
        /// </summary>
        public static string LikeCount {
            get {
                return ResourceManager.GetString("LikeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 链接.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏素材路径.
        /// </summary>
        public static string MaterialPacketUrl {
            get {
                return ResourceManager.GetString("MaterialPacketUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏素材.
        /// </summary>
        public static string MaterialPacketUrl4Game {
            get {
                return ResourceManager.GetString("MaterialPacketUrl4Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 媒体文件ID.
        /// </summary>
        public static string Media_id {
            get {
                return ResourceManager.GetString("Media_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公众号名称.
        /// </summary>
        public static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 线下游戏图片.
        /// </summary>
        public static string OfflineBackground {
            get {
                return ResourceManager.GetString("OfflineBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 线下前景图片.
        /// </summary>
        public static string OfflineForeground {
            get {
                return ResourceManager.GetString("OfflineForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 线上模板背景图片.
        /// </summary>
        public static string OnlineBackground {
            get {
                return ResourceManager.GetString("OnlineBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 线上前景背景图片.
        /// </summary>
        public static string OnlineForeground {
            get {
                return ResourceManager.GetString("OnlineForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始时间.
        /// </summary>
        public static string OpenDate {
            get {
                return ResourceManager.GetString("OpenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenID.
        /// </summary>
        public static string Openid {
            get {
                return ResourceManager.GetString("Openid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动主办方.
        /// </summary>
        public static string Organizer {
            get {
                return ResourceManager.GetString("Organizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外部链接.
        /// </summary>
        public static string OutsideLink {
            get {
                return ResourceManager.GetString("OutsideLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开发者.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动所有者.
        /// </summary>
        public static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 父分组.
        /// </summary>
        public static string ParentGroup {
            get {
                return ResourceManager.GetString("ParentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片地址.
        /// </summary>
        public static string PicUrl {
            get {
                return ResourceManager.GetString("PicUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计划奖品数.
        /// </summary>
        public static string PlanQty {
            get {
                return ResourceManager.GetString("PlanQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 玩家当时年龄.
        /// </summary>
        public static string PlayerAge {
            get {
                return ResourceManager.GetString("PlayerAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 玩家邮箱.
        /// </summary>
        public static string PlayerEmail {
            get {
                return ResourceManager.GetString("PlayerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 玩家当时头像.
        /// </summary>
        public static string PlayerImage {
            get {
                return ResourceManager.GetString("PlayerImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 玩家手机.
        /// </summary>
        public static string PlayerPhone {
            get {
                return ResourceManager.GetString("PlayerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 推送url.
        /// </summary>
        public static string PostUrl {
            get {
                return ResourceManager.GetString("PostUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地区.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 二维码URL.
        /// </summary>
        public static string Qrcode_url {
            get {
                return ResourceManager.GetString("Qrcode_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 二维码Key.
        /// </summary>
        public static string QrCodeKey {
            get {
                return ResourceManager.GetString("QrCodeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 二维码路径.
        /// </summary>
        public static string QRCodesImg {
            get {
                return ResourceManager.GetString("QRCodesImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 二维码状态.
        /// </summary>
        public static string QRStatus {
            get {
                return ResourceManager.GetString("QRStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排队号码.
        /// </summary>
        public static string QueueNum {
            get {
                return ResourceManager.GetString("QueueNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标记.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动规则.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 二维码Scene_id.
        /// </summary>
        public static string Scene_id {
            get {
                return ResourceManager.GetString("Scene_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏得分.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证码.
        /// </summary>
        public static string SecurityCode {
            get {
                return ResourceManager.GetString("SecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏后消息配置名称.
        /// </summary>
        public static string SendWeChatAfterGameTabName {
            get {
                return ResourceManager.GetString("SendWeChatAfterGameTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏前消息配置名称.
        /// </summary>
        public static string SendWeChatBeforGameTabName {
            get {
                return ResourceManager.GetString("SendWeChatBeforGameTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 授权方公众号类型.
        /// </summary>
        public static string Service_type_info {
            get {
                return ResourceManager.GetString("Service_type_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性别.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏分享配置名称.
        /// </summary>
        public static string ShareActionTabName {
            get {
                return ResourceManager.GetString("ShareActionTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否关注.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关注时间.
        /// </summary>
        public static string SubscribeTime {
            get {
                return ResourceManager.GetString("SubscribeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 线下游戏密钥.
        /// </summary>
        public static string SubscriptionKey {
            get {
                return ResourceManager.GetString("SubscriptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支持人数.
        /// </summary>
        public static string SupportedPlayersCount {
            get {
                return ResourceManager.GetString("SupportedPlayersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文本内容.
        /// </summary>
        public static string TextMessage {
            get {
                return ResourceManager.GetString("TextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩略图.
        /// </summary>
        public static string Thumbnail {
            get {
                return ResourceManager.GetString("Thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标题.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消授权时间.
        /// </summary>
        public static string UnAuthorizationTime {
            get {
                return ResourceManager.GetString("UnAuthorizationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unionid.
        /// </summary>
        public static string Unionid {
            get {
                return ResourceManager.GetString("Unionid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取关时间.
        /// </summary>
        public static string UnSubScribeTime {
            get {
                return ResourceManager.GetString("UnSubScribeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 授权方公众号的原始ID.
        /// </summary>
        public static string User_name {
            get {
                return ResourceManager.GetString("User_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地址.
        /// </summary>
        public static string UserAddresses {
            get {
                return ResourceManager.GetString("UserAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 授权方认证类型.
        /// </summary>
        public static string Verify_type_info {
            get {
                return ResourceManager.GetString("Verify_type_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 被浏览次数.
        /// </summary>
        public static string ViewCount {
            get {
                return ResourceManager.GetString("ViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 消息类型.
        /// </summary>
        public static string WeChatType {
            get {
                return ResourceManager.GetString("WeChatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公众号.
        /// </summary>
        public static string WeixinAppID {
            get {
                return ResourceManager.GetString("WeixinAppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态.
        /// </summary>
        public static string WeixinAuthStatus {
            get {
                return ResourceManager.GetString("WeixinAuthStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Func_infos.
        /// </summary>
        public static string WeixinFuncscopeCategoryItem {
            get {
                return ResourceManager.GetString("WeixinFuncscopeCategoryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupid.
        /// </summary>
        public static string WeixinGroupid {
            get {
                return ResourceManager.GetString("WeixinGroupid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 微信信息.
        /// </summary>
        public static string WeixinPublicAccountInfo {
            get {
                return ResourceManager.GetString("WeixinPublicAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公众平台信息.
        /// </summary>
        public static string WeixinPublicAccountInfoID {
            get {
                return ResourceManager.GetString("WeixinPublicAccountInfoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 微信分享.
        /// </summary>
        public static string WeixinShares {
            get {
                return ResourceManager.GetString("WeixinShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeixinUserActions.
        /// </summary>
        public static string WeixinUserActions {
            get {
                return ResourceManager.GetString("WeixinUserActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公众号.
        /// </summary>
        public static string WeixinUserInfo {
            get {
                return ResourceManager.GetString("WeixinUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片地址.
        /// </summary>
        public static string WImagePath {
            get {
                return ResourceManager.GetString("WImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昵称.
        /// </summary>
        public static string WNickname {
            get {
                return ResourceManager.GetString("WNickname", resourceCulture);
            }
        }
    }
}
