//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensingCloud {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SensingCloud.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the award is out..
        /// </summary>
        internal static string API_AwardIsOut {
            get {
                return ResourceManager.GetString("API_AwardIsOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find the award user..
        /// </summary>
        internal static string API_AwardUserNotFound {
            get {
                return ResourceManager.GetString("API_AwardUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the action has been win before. please one action has one change to win.
        /// </summary>
        internal static string API_HasAwardBefore {
            get {
                return ResourceManager.GetString("API_HasAwardBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions happened in invoking api, please contact platform owner for the details, or call 18051589005 directly..
        /// </summary>
        internal static string API_InnerExceptions {
            get {
                return ResourceManager.GetString("API_InnerExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NG.
        /// </summary>
        internal static string API_NG {
            get {
                return ResourceManager.GetString("API_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the specific user has no authority to win the special award.
        /// </summary>
        internal static string API_NoAwardAuthority {
            get {
                return ResourceManager.GetString("API_NoAwardAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the specific award id is not exist in platform..
        /// </summary>
        internal static string API_NoSpecificAward {
            get {
                return ResourceManager.GetString("API_NoSpecificAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string API_OK {
            get {
                return ResourceManager.GetString("API_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input arguments are  not existed in the sensing game platform..
        /// </summary>
        internal static string API_ParamsNotExist {
            get {
                return ResourceManager.GetString("API_ParamsNotExist", resourceCulture);
            }
        }
    }
}
